### PR TITLE
fix tags in setup.cfg

### LINKED ISSUE #45: Error building wheel
Trying to make a multi-stage build with `python:3.7.2-alpine` docker image. First I make a wheel for devtools with `pip wheel devtools --wheel-dir=wheels/`. Then, in the next stage, install wheel `pip install wheels/*`. But I got an error that ```devtools-0.5-py35,py36-none-any.whl is not a supported wheel on this platform.```

The problem is in this piece - `py35,py36`. There should be a period, not a comma.

### PR DESCRIPTION
**Pull request by AlwxSin**
Closes #45

### CODE REVIEW

**Comment by samuelcolvin** [comment]
thanks a lot.

Do you need a new pypi release to use this? If so I'll publish one.

**Comment by AlwxSin** [comment]
@samuelcolvin it will be awesome. For now, I'm using my fork.

**Comment by samuelcolvin** [comment]
ok, let me know if you need a new pypi version.

**Comment by samuelcolvin** [comment]
done.

**Pull request merged**
