### PR TITLE
Type checking improvements

### PR DESCRIPTION
**Pull request by bringhurst**
- Add a PEP 561 marker file (py.typed).
- Run mypy during CI.
- Update black to avoid https://github.com/pallets/click/issues/2225
- Update mkdocs to avoid https://github.com/mkdocs/mkdocs/issues/2799
- Disable mkdocs strict mode to avoid https://github.com/mkdocs/mkdocs/issues/2252

### CODE REVIEW

**Comment by bringhurst** [comment]
Note the ignore lines in `mypy.ini`.

```
#
# Please do not add any additional mypy ignores in this section!
#

[mypy-devtools.utils]
# FIXME: Remove this ignore after fixing type errors.
ignore_errors = true

[mypy-devtools.prettier]
# FIXME: Remove this ignore after fixing type errors.
ignore_errors = true

[mypy-devtools.ansi]
# FIXME: Remove this ignore after fixing type errors.
ignore_errors = true

[mypy-devtools.debug]
# FIXME: Remove this ignore after fixing type errors.
ignore_errors = true
```

This was done so mypy warnings/errors can be fixed in bite-sized PRs. Fixing all of those at once would be quite a large change.

**Comment by bringhurst** [comment]
Discarding due to inactivity.

**Comment by samuelcolvin** [comment]
So sorry, I missed this complete.

Feel free to reopen this and I'll review it this week.

**Comment by samuelcolvin** [comment]
Don't worry, I've fixed this in #107.

**Comment by bringhurst** [comment]
No hard feelings. 😄 

I was just bulk closing old PRs.

TY for fixing it up!

**Pull request closed without merging**
